
#define DB_CREATE_STATEMENT_SUCCESS 2
#define DB_OPEN_SUCCESS 1
#define DB_INVALID_NAME_ERROR -1
#define DB_OPEN_ERROR -2
#define DB_INVALID_STATEMENT_ERROR -3
#define DB_CREATE_STATEMENT_ERROR -4
#define DB_INVALID_STATEMENT_INDICATOR_ERROR -5
#define DB_INVALID_CALLBACK_ERROR -6

#define SELECT_STATEMENT 1
#define NON_SELECT_STATEMENT 0
